<?xml version="1.0"?>
<package format="3">
  <name>respeaker_ros2_recorder</name>
  <version>0.0.0</version>
  <description>ROS 2 Python recorder for ReSpeaker multi-channel audio.</description>

  <maintainer email="kemove@todo.todo">kemove</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>

  <build_depend>rosidl_default_generators</build_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>

  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-pyaudio</exec_depend>
  <exec_depend>python3-soundfile</exec_depend>
  <exec_depend>rosbag2_py</exec_depend>
  <exec_depend>rosidl_runtime_py</exec_depend>

  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
