// Generated by gencpp from file respeaker_ros_recorder/AudioDataStamped.msg
// DO NOT EDIT!


#ifndef RESPEAKER_ROS_RECORDER_MESSAGE_AUDIODATASTAMPED_H
#define RESPEAKER_ROS_RECORDER_MESSAGE_AUDIODATASTAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace respeaker_ros_recorder
{
template <class ContainerAllocator>
struct AudioDataStamped_
{
  typedef AudioDataStamped_<ContainerAllocator> Type;

  AudioDataStamped_()
    : header()
    , sample_rate(0)
    , channels(0)
    , frames(0)
    , data()  {
    }
  AudioDataStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , sample_rate(0)
    , channels(0)
    , frames(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _sample_rate_type;
  _sample_rate_type sample_rate;

   typedef uint32_t _channels_type;
  _channels_type channels;

   typedef uint32_t _frames_type;
  _frames_type frames;

   typedef std::vector<int16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int16_t>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::respeaker_ros_recorder::AudioDataStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::respeaker_ros_recorder::AudioDataStamped_<ContainerAllocator> const> ConstPtr;

}; // struct AudioDataStamped_

typedef ::respeaker_ros_recorder::AudioDataStamped_<std::allocator<void> > AudioDataStamped;

typedef boost::shared_ptr< ::respeaker_ros_recorder::AudioDataStamped > AudioDataStampedPtr;
typedef boost::shared_ptr< ::respeaker_ros_recorder::AudioDataStamped const> AudioDataStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::respeaker_ros_recorder::AudioDataStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::respeaker_ros_recorder::AudioDataStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::respeaker_ros_recorder::AudioDataStamped_<ContainerAllocator1> & lhs, const ::respeaker_ros_recorder::AudioDataStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.sample_rate == rhs.sample_rate &&
    lhs.channels == rhs.channels &&
    lhs.frames == rhs.frames &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::respeaker_ros_recorder::AudioDataStamped_<ContainerAllocator1> & lhs, const ::respeaker_ros_recorder::AudioDataStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace respeaker_ros_recorder

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::respeaker_ros_recorder::AudioDataStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::respeaker_ros_recorder::AudioDataStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::respeaker_ros_recorder::AudioDataStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::respeaker_ros_recorder::AudioDataStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::respeaker_ros_recorder::AudioDataStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::respeaker_ros_recorder::AudioDataStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::respeaker_ros_recorder::AudioDataStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "54015d5fe0aee8071806c47e9f87c566";
  }

  static const char* value(const ::respeaker_ros_recorder::AudioDataStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x54015d5fe0aee807ULL;
  static const uint64_t static_value2 = 0x1806c47e9f87c566ULL;
};

template<class ContainerAllocator>
struct DataType< ::respeaker_ros_recorder::AudioDataStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "respeaker_ros_recorder/AudioDataStamped";
  }

  static const char* value(const ::respeaker_ros_recorder::AudioDataStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::respeaker_ros_recorder::AudioDataStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"uint32 sample_rate\n"
"uint32 channels\n"
"uint32 frames\n"
"int16[] data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::respeaker_ros_recorder::AudioDataStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::respeaker_ros_recorder::AudioDataStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.sample_rate);
      stream.next(m.channels);
      stream.next(m.frames);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AudioDataStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::respeaker_ros_recorder::AudioDataStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::respeaker_ros_recorder::AudioDataStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "sample_rate: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.sample_rate);
    s << indent << "channels: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.channels);
    s << indent << "frames: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.frames);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RESPEAKER_ROS_RECORDER_MESSAGE_AUDIODATASTAMPED_H
